### PR TITLE
Added Konrad profile

### PR DESCRIPTION
**Pull request by konradoo11**
Added my profile.

### CODE REVIEW

**Comment by oeway** [comment]
For the `content/authors/konrad.md` file, that should be deleted right?

**Comment by konradoo11** [comment]
> For the `content/authors/konrad.md` file, that should be deleted right?

Yes, that's right. It accidentally got included.

**Comment by oeway** [comment]
> > For the `content/authors/konrad.md` file, that should be deleted right?
> 
> Yes, that's right. It accidentally got included.

Please remove it so I can merge it.

**Comment by konradoo11** [comment]
> > > For the `content/authors/konrad.md` file, that should be deleted right?
> > 
> > 
> > Yes, that's right. It accidentally got included.
> 
> Please remove it so I can merge it.

**Comment by konradoo11** [comment]
@oeway I accidentally closed the PR. It is now reopened, updated and ready for review and merging.

**Comment by oeway** [comment]
Thanks!

**Pull request merged**
